name: Integration Tests

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

env:
  ZEKLIN_SERVER_URL: ${{ secrets.STAGING_ZEKLIN_SERVER_URL }}

jobs:
  test-action:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: zeklin-action test - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - run: env
      - uses: actions/checkout@v4.0.0

      - name: Test Action
        id: test-action
        uses: ./
        with:
          api-key: ${{ secrets.STAGING_ZEKLIN_API_KEY }}
          api-key-id: ${{ secrets.STAGING_ZEKLIN_API_KEY_ID }}
          output-file-path: 'jmh_samples_all.json'
          workdir: "."
          cmd: |
            echo 'hello world'
            ls

      - name: Test Failing Action
        id: test-failing-action
        continue-on-error: true
        uses: ./
        with:
          api-key: ${{ secrets.STAGING_ZEKLIN_API_KEY }}
          api-key-id: ${{ secrets.STAGING_ZEKLIN_API_KEY_ID }}
          cmd: sh -c "if true; then exit 1; fi"
          output-file-path: '../empty_report.json'
