name: Integration Tests

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

env:
  ZEKLIN_SERVER_URL: ${{ secrets.ZEKLIN_SERVER_URL }}

jobs:
  test-action:
    name: zeklin-action test
    runs-on: ubuntu-latest
    steps:
      - run: env
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Test Action
        id: test-action
        uses: ./
        with:
          api-key: ${{ secrets.ZEKLIN_API_KEY }}
          api-key-id: ${{ secrets.ZEKLIN_API_KEY_ID }}
          output-file-path: 'empty_report.json'
          workdir: "."
          cmd: |
            echo 'hello world'
            ls

      - name: Test Failing Action
        id: test-failing-action
        continue-on-error: true
        uses: ./
        with:
          api-key: ${{ secrets.ZEKLIN_API_KEY }}
          api-key-id: ${{ secrets.ZEKLIN_API_KEY_ID }}
          cmd: sh -c "if true; then exit 1; fi"
          output-file-path: '../empty_report.json'

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"

  test-jmh:
    name: zeklin-action with JMH
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xms6g -Xmx6g -XX:+UseG1GC
      JDK_JAVA_OPTIONS: -Xms6g -Xmx6g -XX:+UseG1GC # See https://stackoverflow.com/a/73708006
    strategy:
      fail-fast: false
      matrix:
        jmh-samples: [ "0", "1", "2", "3.0", "3.1" ]
    steps:
      - run: env
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: zeklin-io/jmh
          ref: master
          path: jmh-dir

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven
          check-latest: true

      - name: Build project
        run: |
          cd jmh-dir
          mvn clean package -DskipTests

      - name: Test Action with JMH - ${{ matrix.jmh-samples }}
        uses: ./
        env:
          NODE_DEBUG: http # See: https://github.com/actions/toolkit/tree/main/packages/http-client#debugging
        with:
          api-key: ${{ secrets.ZEKLIN_API_KEY }}
          api-key-id: ${{ secrets.ZEKLIN_API_KEY_ID }}
          workdir: jmh-dir/jmh-samples-${{ matrix.jmh-samples }}
          output-file-path: 'reports.json'
          cmd: |
            java -jar target/benchmarks.jar -wi 2 -i 2 -r 1 -w 1 -t 1 -f 1 -foe true -rff reports.json -rf json
            ls
